/* eslint-disable */
/* global WebImporter */

// AUTO-GENERATED by tools/importer/gen-import-scripts.mjs — one script per template.
// Orchestrates block parsers + site-wide transformers (cleanup -> links -> sections).

// PARSER IMPORTS
import accordionParser from './parsers/accordion.js';

// TRANSFORMER IMPORTS
import cleanupTransformer from './transformers/wknd-cleanup.js';
import linksTransformer from './transformers/wknd-links.js';
import sectionsTransformer from './transformers/wknd-sections.js';

// PARSER REGISTRY
const parsers = {
  'accordion': accordionParser,
};

// PAGE TEMPLATE CONFIGURATION — embedded from page-templates.json
const PAGE_TEMPLATE = {
  "name": "faqs",
  "description": "FAQs page. Two-column fixed layout: main column (underlined H1 'FAQs', hero photo, intro paragraph, and a 7-item Q/A accordion -> accordion block) + a 'Need more help?' sidebar (heading + contact paragraph). Reuses the accordion block; sidebar and intro are default content.",
  "urls": [
    "https://wknd.site/us/en/faqs.html"
  ],
  "blocks": [
    {
      "name": "accordion",
      "instances": [
        "div.accordion.panelcontainer"
      ]
    }
  ],
  "sections": [
    {
      "id": "s1",
      "name": "Main FAQ content",
      "selector": "main div.container.responsivegrid.aem-GridColumn--default--8",
      "style": null,
      "blocks": [
        "accordion"
      ],
      "defaultContent": [
        "div.title.cmp-title--underline",
        "main div.container.responsivegrid.aem-GridColumn--default--8 div.image",
        "main div.container.responsivegrid.aem-GridColumn--default--8 div.text"
      ]
    },
    {
      "id": "s2",
      "name": "Need more help? (sidebar)",
      "selector": "main div.container.responsivegrid.aem-GridColumn--default--3",
      "style": null,
      "blocks": [],
      "defaultContent": [
        "main div.container.responsivegrid.aem-GridColumn--default--3 div.title",
        "main div.container.responsivegrid.aem-GridColumn--default--3 div.text"
      ]
    }
  ]
};

// TRANSFORMER REGISTRY (cleanup + links always run; sections only for multi-section templates)
const transformers = [
  cleanupTransformer,
  linksTransformer,
  ...(PAGE_TEMPLATE.sections && PAGE_TEMPLATE.sections.length > 1 ? [sectionsTransformer] : []),
];

/**
 * Execute all page transformers for a specific hook.
 * @param {string} hookName 'beforeTransform' | 'afterTransform'
 * @param {Element} element DOM element (document.body)
 * @param {Object} payload { document, url, html, params }
 */
function executeTransformers(hookName, element, payload) {
  const enhancedPayload = { ...payload, template: PAGE_TEMPLATE };
  transformers.forEach((transformerFn) => {
    try {
      transformerFn.call(null, hookName, element, enhancedPayload);
    } catch (e) {
      console.error(`Transformer failed at ${hookName}:`, e);
    }
  });
}

/**
 * Find all blocks on the page based on the embedded template configuration.
 * @param {Document} document
 * @param {Object} template PAGE_TEMPLATE
 * @returns {Array} block instances found on the page
 */
function findBlocksOnPage(document, template) {
  const pageBlocks = [];
  template.blocks.forEach((blockDef) => {
    blockDef.instances.forEach((selector) => {
      let elements = [];
      try {
        elements = document.querySelectorAll(selector);
      } catch (e) {
        console.warn(`Invalid selector for "${blockDef.name}": ${selector}`);
        return;
      }
      if (elements.length === 0) {
        console.warn(`Block "${blockDef.name}" selector not found: ${selector}`);
      }
      elements.forEach((element) => {
        pageBlocks.push({
          name: blockDef.name,
          selector,
          element,
          section: blockDef.section || null,
        });
      });
    });
  });
  console.log(`Found ${pageBlocks.length} block instances on page`);
  return pageBlocks;
}

export default {
  transform: (payload) => {
    const {
      document, url, html, params,
    } = payload;

    const main = document.body;

    // 1. beforeTransform (initial cleanup)
    executeTransformers('beforeTransform', main, payload);

    // 2. Discover blocks from embedded template
    const pageBlocks = findBlocksOnPage(document, PAGE_TEMPLATE);

    // 3. Parse each block (skip elements already replaced by a prior parser)
    pageBlocks.forEach((block) => {
      if (!block.element.parentNode) return;
      const parser = parsers[block.name];
      if (parser) {
        try {
          parser(block.element, { document, url, params });
        } catch (e) {
          console.error(`Failed to parse ${block.name} (${block.selector}):`, e);
        }
      } else {
        console.warn(`No parser found for block: ${block.name}`);
      }
    });

    // 4. afterTransform (final cleanup + link remap + section breaks/metadata)
    executeTransformers('afterTransform', main, payload);

    // 5. WebImporter built-in rules
    const hr = document.createElement('hr');
    main.appendChild(hr);
    WebImporter.rules.createMetadata(main, document);
    WebImporter.rules.transformBackgroundImages(main, document);
    WebImporter.rules.adjustImageUrls(main, url, params.originalURL);

    // 6. Sanitized path (map root/homepage to /index to avoid empty-path crash)
    const rawPath = new URL(params.originalURL).pathname
      .replace(/\/$/, '')
      .replace(/\.html?$/, '');
    const path = WebImporter.FileUtils.sanitizePath(rawPath === '' ? '/index' : rawPath);

    return [{
      element: main,
      path,
      report: {
        title: document.title,
        template: PAGE_TEMPLATE.name,
        blocks: pageBlocks.map((b) => b.name),
      },
    }];
  },
};
